name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flare_flutter: ^1.5.4
  provider: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/progress.flr
   - assets/loader.flr
   - assets/solutions/pexels-photo-414612.jpeg
